name: Widget-server pipe

on:
  push:
    branches:
      - 'main'
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        id: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Generete tag
        id: generate_tag
        run:
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push the image to AWS ECR
        id: build-push-image
        env:
          ECR_REGISTRY: ${{steps.login_ecr.outputs.registry}}
          ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
          IMAGE_TAG: ${{ steps.generate_tag.outputs.sha }}
          ECR_CONFIG: ${{ vars.ECR_REGISTRY/vars.ECR_REPOSITORY:vars.IMAGE_TAG }}
        run: |
          docker build -t $ECR_CONFIG .
          docker push $ECR_CONFIG

